baseURL = 'https://sreehari32.github.io/blog/'
languageCode = 'en-us'
title = 'Le Blog'
theme='HugoTex'

paginate = 3

DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Params.author]
  name = "Sreehari Rajamohan"
  abstract = """
  I'm a data enthusiast from India.
  My primary interest lies in the area of natural language processing.
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"
 


[Params]
  darkmode = true
